name: 'formatting'
description: 'CI formatting check'
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps: 
      - name: Install Uncrustify
        run: sudo apt-get install uncrustify

      